#!/usr/bin/env python3
import os, re, json, subprocess

ORIGINAL_DIR = "original"
MUSIC_DIR    = "music"
OUTPUT_FILE  = "songs.js"
EXTENSIONS   = {".mp3", ".wav", ".ogg", ".flac", ".aac", ".m4a"}

os.makedirs(MUSIC_DIR, exist_ok=True)

# 1. Wipe /music
for f in os.listdir(MUSIC_DIR):
    if os.path.splitext(f)[1].lower() in EXTENSIONS:
        os.remove(os.path.join(MUSIC_DIR, f))

# 2. Cut every file in /original to 20s and save to /music
files = sorted(f for f in os.listdir(ORIGINAL_DIR) if os.path.splitext(f)[1].lower() in EXTENSIONS)

for filename in files:
    src = os.path.join(ORIGINAL_DIR, filename)
    dst = os.path.join(MUSIC_DIR, filename)
    subprocess.run([
        "ffmpeg", "-y", "-i", src,
        "-t", "20",
        "-ar", "44100", "-ac", "2", "-b:a", "192k",
        dst
    ], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    print(f"✅ {filename}")

# 3. Rebuild songs.js
songs = []
for filename in sorted(f for f in os.listdir(MUSIC_DIR) if os.path.splitext(f)[1].lower() in EXTENSIONS):
    name = re.sub(r"^\d+[\s.\-]+", "", os.path.splitext(filename)[0]).strip()
    parts = [p.strip() for p in name.split(" - ")]
    songs.append({
        "file": f"music/{filename}",
        "title": " - ".join(parts[1:]) if len(parts) >= 2 else parts[0],
        "artist": parts[0] if len(parts) >= 2 else None,
        "genre": None
    })

with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by build.py\n")
    f.write("const SONGS = " + json.dumps(songs, indent=2, ensure_ascii=False) + ";\n")

print(f"\n📋 {len(songs)} song(s) written to songs.js")
