#!/usr/bin/env python3
"""
generate.py — Scans the /music/ folder and generates songs.js for Earworm.
Run: python generate.py
"""

import os
import json
import re

MUSIC_DIR = "music"
OUTPUT_FILE = "songs.js"
EXTENSIONS = {".mp3", ".wav", ".ogg", ".flac", ".aac", ".m4a"}


def parse_filename(filename):
    """
    Try to extract title and artist from filename.
    Supports common patterns:
      - "Artist - Title.mp3"
      - "Title.mp3"
      - "01 - Artist - Title.mp3"
    """
    name = os.path.splitext(filename)[0]

    # Remove leading track numbers like "01 - " or "01. "
    name = re.sub(r"^\d+[\s.\-]+", "", name).strip()

    parts = [p.strip() for p in name.split(" - ")]

    if len(parts) >= 2:
        return {"artist": parts[0], "title": " - ".join(parts[1:])}
    else:
        return {"artist": None, "title": name}


def main():
    if not os.path.isdir(MUSIC_DIR):
        print(f"❌ Folder '{MUSIC_DIR}' not found. Create it and add your MP3s.")
        return

    files = sorted(
        f for f in os.listdir(MUSIC_DIR)
        if os.path.splitext(f)[1].lower() in EXTENSIONS
    )

    if not files:
        print(f"❌ No audio files found in '{MUSIC_DIR}/'")
        return

    songs = []
    for filename in files:
        parsed = parse_filename(filename)
        songs.append({
            "file": f"music/{filename}",
            "title": parsed["title"],
            "artist": parsed["artist"],
            "genre": None  # Add manually in songs.js if you want
        })

    # Write as a JS module so it works without a server config
    js_content = "// Auto-generated by generate.py — do not edit manually\n"
    js_content += "const SONGS = " + json.dumps(songs, indent=2, ensure_ascii=False) + ";\n"

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"✅ {len(songs)} songs written to {OUTPUT_FILE}")
    for s in songs:
        artist = s["artist"] or "Unknown"
        print(f"   • {artist} — {s['title']}")


if __name__ == "__main__":
    main()
