// Auto-generated by build.py
const SONGS = [
  {
    "file": "music/505.mp3",
    "title": "505",
    "artist": null,
    "genre": null
  },
  {
    "file": "music/Adele - Someone Like You (Official Music Video).mp3",
    "title": "Someone Like You (Official Music Video)",
    "artist": "Adele",
    "genre": null
  },
  {
    "file": "music/Arctic Monkeys - Do I Wanna Know (Official Video).mp3",
    "title": "Do I Wanna Know (Official Video)",
    "artist": "Arctic Monkeys",
    "genre": null
  },
  {
    "file": "music/Ariana Grande - 7 rings (Official Video).mp3",
    "title": "7 rings (Official Video)",
    "artist": "Ariana Grande",
    "genre": null
  },
  {
    "file": "music/Avicii - Wake Me Up (Official Video).mp3",
    "title": "Wake Me Up (Official Video)",
    "artist": "Avicii",
    "genre": null
  },
  {
    "file": "music/Benson Boone - Beautiful Things (Official Music Video).mp3",
    "title": "Beautiful Things (Official Music Video)",
    "artist": "Benson Boone",
    "genre": null
  },
  {
    "file": "music/Billie Eilish - BIRDS OF A FEATHER (Official Music Video).mp3",
    "title": "BIRDS OF A FEATHER (Official Music Video)",
    "artist": "Billie Eilish",
    "genre": null
  },
  {
    "file": "music/Billie Eilish - bad guy.mp3",
    "title": "bad guy",
    "artist": "Billie Eilish",
    "genre": null
  },
  {
    "file": "music/Billie Eilish, Khalid - lovely.mp3",
    "title": "lovely",
    "artist": "Billie Eilish, Khalid",
    "genre": null
  },
  {
    "file": "music/Bruno Mars - Just The Way You Are (Official Music Video).mp3",
    "title": "Just The Way You Are (Official Music Video)",
    "artist": "Bruno Mars",
    "genre": null
  },
  {
    "file": "music/Bruno Mars - Locked Out Of Heaven (Official Music Video).mp3",
    "title": "Locked Out Of Heaven (Official Music Video)",
    "artist": "Bruno Mars",
    "genre": null
  },
  {
    "file": "music/Bruno Mars - That’s What I Like [Official Music Video].mp3",
    "title": "That’s What I Like [Official Music Video]",
    "artist": "Bruno Mars",
    "genre": null
  },
  {
    "file": "music/Bruno Mars - When I Was Your Man (Official Music Video).mp3",
    "title": "When I Was Your Man (Official Music Video)",
    "artist": "Bruno Mars",
    "genre": null
  },
  {
    "file": "music/Calvin Harris, Dua Lipa - One Kiss (Official Video).mp3",
    "title": "One Kiss (Official Video)",
    "artist": "Calvin Harris, Dua Lipa",
    "genre": null
  },
  {
    "file": "music/Coldplay - The Scientist (Official 4K Video).mp3",
    "title": "The Scientist (Official 4K Video)",
    "artist": "Coldplay",
    "genre": null
  },
  {
    "file": "music/Coldplay - Viva La Vida (Official Video).mp3",
    "title": "Viva La Vida (Official Video)",
    "artist": "Coldplay",
    "genre": null
  },
  {
    "file": "music/Coldplay - Yellow (Official Video).mp3",
    "title": "Yellow (Official Video)",
    "artist": "Coldplay",
    "genre": null
  },
  {
    "file": "music/DJ Snake - Let Me Love You ft. Justin Bieber.mp3",
    "title": "Let Me Love You ft. Justin Bieber",
    "artist": "DJ Snake",
    "genre": null
  },
  {
    "file": "music/Die For You.mp3",
    "title": "Die For You",
    "artist": null,
    "genre": null
  },
  {
    "file": "music/Drake - God's Plan.mp3",
    "title": "God's Plan",
    "artist": "Drake",
    "genre": null
  },
  {
    "file": "music/Dua Lipa - Don't Start Now (Official Music Video).mp3",
    "title": "Don't Start Now (Official Music Video)",
    "artist": "Dua Lipa",
    "genre": null
  },
  {
    "file": "music/Ed Sheeran - Perfect (Official Music Video).mp3",
    "title": "Perfect (Official Music Video)",
    "artist": "Ed Sheeran",
    "genre": null
  },
  {
    "file": "music/Ed Sheeran - Photograph (Official Music Video).mp3",
    "title": "Photograph (Official Music Video)",
    "artist": "Ed Sheeran",
    "genre": null
  },
  {
    "file": "music/Ed Sheeran - Shape of You (Official Music Video).mp3",
    "title": "Shape of You (Official Music Video)",
    "artist": "Ed Sheeran",
    "genre": null
  },
  {
    "file": "music/Ed Sheeran - Thinking Out Loud (Official Music Video).mp3",
    "title": "Thinking Out Loud (Official Music Video)",
    "artist": "Ed Sheeran",
    "genre": null
  },
  {
    "file": "music/Elton John, Dua Lipa - Cold Heart (PNAU Remix) (Official Video).mp3",
    "title": "Cold Heart (PNAU Remix) (Official Video)",
    "artist": "Elton John, Dua Lipa",
    "genre": null
  },
  {
    "file": "music/Eminem - Lose Yourself [HD].mp3",
    "title": "Lose Yourself [HD]",
    "artist": "Eminem",
    "genre": null
  },
  {
    "file": "music/Eminem - Without Me (Official Music Video).mp3",
    "title": "Without Me (Official Music Video)",
    "artist": "Eminem",
    "genre": null
  },
  {
    "file": "music/Fleetwood Mac - Dreams (Official Music Video) [4K].mp3",
    "title": "Dreams (Official Music Video) [4K]",
    "artist": "Fleetwood Mac",
    "genre": null
  },
  {
    "file": "music/French Montana - Unforgettable ft. Swae Lee.mp3",
    "title": "Unforgettable ft. Swae Lee",
    "artist": "French Montana",
    "genre": null
  },
  {
    "file": "music/Glass Animals - Heat Waves (Official Video).mp3",
    "title": "Heat Waves (Official Video)",
    "artist": "Glass Animals",
    "genre": null
  },
  {
    "file": "music/Goo Goo Dolls – Iris [Official Music Video] [4K Remaster].mp3",
    "title": "Goo Goo Dolls – Iris [Official Music Video] [4K Remaster]",
    "artist": null,
    "genre": null
  },
  {
    "file": "music/Guns N' Roses - Sweet Child O' Mine (Official Music Video).mp3",
    "title": "Sweet Child O' Mine (Official Music Video)",
    "artist": "Guns N' Roses",
    "genre": null
  },
  {
    "file": "music/Harry Styles - As It Was (Official Video).mp3",
    "title": "As It Was (Official Video)",
    "artist": "Harry Styles",
    "genre": null
  },
  {
    "file": "music/Harry Styles - Watermelon Sugar (Official Video).mp3",
    "title": "Watermelon Sugar (Official Video)",
    "artist": "Harry Styles",
    "genre": null
  },
  {
    "file": "music/Hozier - Take Me To Church.mp3",
    "title": "Take Me To Church",
    "artist": "Hozier",
    "genre": null
  },
  {
    "file": "music/I Wanna Be Yours.mp3",
    "title": "I Wanna Be Yours",
    "artist": null,
    "genre": null
  },
  {
    "file": "music/Imagine Dragons - Believer (Official Music Video).mp3",
    "title": "Believer (Official Music Video)",
    "artist": "Imagine Dragons",
    "genre": null
  },
  {
    "file": "music/Imagine Dragons - Demons (Official Music Video).mp3",
    "title": "Demons (Official Music Video)",
    "artist": "Imagine Dragons",
    "genre": null
  },
  {
    "file": "music/Imagine Dragons - Thunder.mp3",
    "title": "Thunder",
    "artist": "Imagine Dragons",
    "genre": null
  },
  {
    "file": "music/In The End [Official HD Music Video] - Linkin Park.mp3",
    "title": "Linkin Park",
    "artist": "In The End [Official HD Music Video]",
    "genre": null
  },
  {
    "file": "music/James Arthur - Say You Won't Let Go.mp3",
    "title": "Say You Won't Let Go",
    "artist": "James Arthur",
    "genre": null
  },
  {
    "file": "music/John Legend - All of Me (Official Video).mp3",
    "title": "All of Me (Official Video)",
    "artist": "John Legend",
    "genre": null
  },
  {
    "file": "music/Journey - Don't Stop Believin' (Official Audio).mp3",
    "title": "Don't Stop Believin' (Official Audio)",
    "artist": "Journey",
    "genre": null
  },
  {
    "file": "music/Juice WRLD - Lucid Dreams (Official Music Video).mp3",
    "title": "Lucid Dreams (Official Music Video)",
    "artist": "Juice WRLD",
    "genre": null
  },
  {
    "file": "music/Justin Bieber - Love Yourself (PURPOSE  The Movement).mp3",
    "title": "Love Yourself (PURPOSE  The Movement)",
    "artist": "Justin Bieber",
    "genre": null
  },
  {
    "file": "music/Justin Bieber - Sorry (PURPOSE  The Movement).mp3",
    "title": "Sorry (PURPOSE  The Movement)",
    "artist": "Justin Bieber",
    "genre": null
  },
  {
    "file": "music/Kendrick Lamar - HUMBLE..mp3",
    "title": "HUMBLE.",
    "artist": "Kendrick Lamar",
    "genre": null
  },
  {
    "file": "music/Kendrick Lamar, SZA - All The Stars.mp3",
    "title": "All The Stars",
    "artist": "Kendrick Lamar, SZA",
    "genre": null
  },
  {
    "file": "music/Lady Gaga, Bradley Cooper - Shallow (from A Star Is Born) (Official Music Video).mp3",
    "title": "Shallow (from A Star Is Born) (Official Music Video)",
    "artist": "Lady Gaga, Bradley Cooper",
    "genre": null
  },
  {
    "file": "music/Lady Gaga, Bruno Mars - Die With A Smile (Official Music Video).mp3",
    "title": "Die With A Smile (Official Music Video)",
    "artist": "Lady Gaga, Bruno Mars",
    "genre": null
  },
  {
    "file": "music/Lewis Capaldi - Someone You Loved.mp3",
    "title": "Someone You Loved",
    "artist": "Lewis Capaldi",
    "genre": null
  },
  {
    "file": "music/Lord Huron - The Night We Met.mp3",
    "title": "The Night We Met",
    "artist": "Lord Huron",
    "genre": null
  },
  {
    "file": "music/MACKLEMORE & RYAN LEWIS - CAN'T HOLD US FEAT. RAY DALTON (OFFICIAL MUSIC VIDEO).mp3",
    "title": "CAN'T HOLD US FEAT. RAY DALTON (OFFICIAL MUSIC VIDEO)",
    "artist": "MACKLEMORE & RYAN LEWIS",
    "genre": null
  },
  {
    "file": "music/Major Lazer & DJ Snake - Lean On (feat. MØ) [Official 4K Music Video].mp3",
    "title": "Lean On (feat. MØ) [Official 4K Music Video]",
    "artist": "Major Lazer & DJ Snake",
    "genre": null
  },
  {
    "file": "music/Mark Ronson - Uptown Funk (Official Video) ft. Bruno Mars.mp3",
    "title": "Uptown Funk (Official Video) ft. Bruno Mars",
    "artist": "Mark Ronson",
    "genre": null
  },
  {
    "file": "music/Maroon 5 - Payphone ft. Wiz Khalifa (Explicit) (Official Music Video).mp3",
    "title": "Payphone ft. Wiz Khalifa (Explicit) (Official Music Video)",
    "artist": "Maroon 5",
    "genre": null
  },
  {
    "file": "music/Marshmello ft. Bastille - Happier (Clip officiel).mp3",
    "title": "Happier (Clip officiel)",
    "artist": "Marshmello ft. Bastille",
    "genre": null
  },
  {
    "file": "music/Michael Jackson - Billie Jean (Official Video).mp3",
    "title": "Billie Jean (Official Video)",
    "artist": "Michael Jackson",
    "genre": null
  },
  {
    "file": "music/Miley Cyrus - Flowers (Official Video).mp3",
    "title": "Flowers (Official Video)",
    "artist": "Miley Cyrus",
    "genre": null
  },
  {
    "file": "music/Nirvana - Smells Like Teen Spirit (Official Music Video).mp3",
    "title": "Smells Like Teen Spirit (Official Music Video)",
    "artist": "Nirvana",
    "genre": null
  },
  {
    "file": "music/No Role Modelz.mp3",
    "title": "No Role Modelz",
    "artist": null,
    "genre": null
  },
  {
    "file": "music/Numb (Official Music Video) [4K UPGRADE] – Linkin Park.mp3",
    "title": "Numb (Official Music Video) [4K UPGRADE] – Linkin Park",
    "artist": null,
    "genre": null
  },
  {
    "file": "music/Oasis - Wonderwall (Official Video).mp3",
    "title": "Wonderwall (Official Video)",
    "artist": "Oasis",
    "genre": null
  },
  {
    "file": "music/Olivia Rodrigo - drivers license (Official Video).mp3",
    "title": "drivers license (Official Video)",
    "artist": "Olivia Rodrigo",
    "genre": null
  },
  {
    "file": "music/Olivia Rodrigo - good 4 u (Official Video).mp3",
    "title": "good 4 u (Official Video)",
    "artist": "Olivia Rodrigo",
    "genre": null
  },
  {
    "file": "music/One Dance-Drake (feat. Wizkid & Kyla).mp3",
    "title": "One Dance-Drake (feat. Wizkid & Kyla)",
    "artist": null,
    "genre": null
  },
  {
    "file": "music/OneRepublic - Counting Stars.mp3",
    "title": "Counting Stars",
    "artist": "OneRepublic",
    "genre": null
  },
  {
    "file": "music/Passenger   Let Her Go (Official Video).mp3",
    "title": "Passenger   Let Her Go (Official Video)",
    "artist": null,
    "genre": null
  },
  {
    "file": "music/Post Malone - Circles.mp3",
    "title": "Circles",
    "artist": "Post Malone",
    "genre": null
  },
  {
    "file": "music/Post Malone - rockstar (Official Music Video) ft. 21 Savage.mp3",
    "title": "rockstar (Official Music Video) ft. 21 Savage",
    "artist": "Post Malone",
    "genre": null
  },
  {
    "file": "music/Post Malone, Swae Lee - Sunflower (Spider-Man Into the Spider-Verse).mp3",
    "title": "Sunflower (Spider-Man Into the Spider-Verse)",
    "artist": "Post Malone, Swae Lee",
    "genre": null
  },
  {
    "file": "music/Queen - Don't Stop Me Now (Official Video).mp3",
    "title": "Don't Stop Me Now (Official Video)",
    "artist": "Queen",
    "genre": null
  },
  {
    "file": "music/Queen – Bohemian Rhapsody (Official Video Remastered).mp3",
    "title": "Queen – Bohemian Rhapsody (Official Video Remastered)",
    "artist": null,
    "genre": null
  },
  {
    "file": "music/Radiohead - Creep.mp3",
    "title": "Creep",
    "artist": "Radiohead",
    "genre": null
  },
  {
    "file": "music/Rick Astley - Never Gonna Give You Up (Official Music Video).mp3",
    "title": "Never Gonna Give You Up (Official Music Video)",
    "artist": "Rick Astley",
    "genre": null
  },
  {
    "file": "music/SEE YOU AGAIN featuring Kali Uchis.mp3",
    "title": "SEE YOU AGAIN featuring Kali Uchis",
    "artist": null,
    "genre": null
  },
  {
    "file": "music/SZA - Kill Bill (Official Audio).mp3",
    "title": "Kill Bill (Official Audio)",
    "artist": "SZA",
    "genre": null
  },
  {
    "file": "music/Sabrina Carpenter - Espresso.mp3",
    "title": "Espresso",
    "artist": "Sabrina Carpenter",
    "genre": null
  },
  {
    "file": "music/Shawn Mendes - There's Nothing Holdin' Me Back (Official Music Video).mp3",
    "title": "There's Nothing Holdin' Me Back (Official Music Video)",
    "artist": "Shawn Mendes",
    "genre": null
  },
  {
    "file": "music/Shawn Mendes - Treat You Better.mp3",
    "title": "Treat You Better",
    "artist": "Shawn Mendes",
    "genre": null
  },
  {
    "file": "music/Shawn Mendes, Camila Cabello - Señorita.mp3",
    "title": "Señorita",
    "artist": "Shawn Mendes, Camila Cabello",
    "genre": null
  },
  {
    "file": "music/TONES AND I - DANCE MONKEY (OFFICIAL VIDEO).mp3",
    "title": "DANCE MONKEY (OFFICIAL VIDEO)",
    "artist": "TONES AND I",
    "genre": null
  },
  {
    "file": "music/Taylor Swift - Cruel Summer (Official Audio).mp3",
    "title": "Cruel Summer (Official Audio)",
    "artist": "Taylor Swift",
    "genre": null
  },
  {
    "file": "music/The Chainsmokers & Coldplay - Something Just Like This (Official Lyric Video).mp3",
    "title": "Something Just Like This (Official Lyric Video)",
    "artist": "The Chainsmokers & Coldplay",
    "genre": null
  },
  {
    "file": "music/The Chainsmokers - Closer (Lyric) ft. Halsey.mp3",
    "title": "Closer (Lyric) ft. Halsey",
    "artist": "The Chainsmokers",
    "genre": null
  },
  {
    "file": "music/The Kid LAROI, Justin Bieber - STAY (Official Video).mp3",
    "title": "STAY (Official Video)",
    "artist": "The Kid LAROI, Justin Bieber",
    "genre": null
  },
  {
    "file": "music/The Killers - Mr. Brightside (Official Music Video).mp3",
    "title": "Mr. Brightside (Official Music Video)",
    "artist": "The Killers",
    "genre": null
  },
  {
    "file": "music/The Neighbourhood - Sweater Weather (Official Video).mp3",
    "title": "Sweater Weather (Official Video)",
    "artist": "The Neighbourhood",
    "genre": null
  },
  {
    "file": "music/The Police - Every Breath You Take (Official Music Video).mp3",
    "title": "Every Breath You Take (Official Music Video)",
    "artist": "The Police",
    "genre": null
  },
  {
    "file": "music/The Weeknd - Blinding Lights (Official Audio).mp3",
    "title": "Blinding Lights (Official Audio)",
    "artist": "The Weeknd",
    "genre": null
  },
  {
    "file": "music/The Weeknd - Save Your Tears (Official Music Video).mp3",
    "title": "Save Your Tears (Official Music Video)",
    "artist": "The Weeknd",
    "genre": null
  },
  {
    "file": "music/The Weeknd - Starboy ft. Daft Punk (Official Lyric Video).mp3",
    "title": "Starboy ft. Daft Punk (Official Lyric Video)",
    "artist": "The Weeknd",
    "genre": null
  },
  {
    "file": "music/The Weeknd - The Hills.mp3",
    "title": "The Hills",
    "artist": "The Weeknd",
    "genre": null
  },
  {
    "file": "music/Tom Odell - Another Love (Official Video).mp3",
    "title": "Another Love (Official Video)",
    "artist": "Tom Odell",
    "genre": null
  },
  {
    "file": "music/Travis Scott - SICKO MODE (Official Video) ft. Drake.mp3",
    "title": "SICKO MODE (Official Video) ft. Drake",
    "artist": "Travis Scott",
    "genre": null
  },
  {
    "file": "music/Travis Scott - goosebumps (Official Video) ft. Kendrick Lamar.mp3",
    "title": "goosebumps (Official Video) ft. Kendrick Lamar",
    "artist": "Travis Scott",
    "genre": null
  },
  {
    "file": "music/Vance Joy - 'Riptide' Official Video.mp3",
    "title": "'Riptide' Official Video",
    "artist": "Vance Joy",
    "genre": null
  },
  {
    "file": "music/a-ha - Take On Me (Vidéo Officielle).mp3",
    "title": "Take On Me (Vidéo Officielle)",
    "artist": "a-ha",
    "genre": null
  },
  {
    "file": "music/twenty one pilots Stressed Out [OFFICIAL VIDEO].mp3",
    "title": "twenty one pilots Stressed Out [OFFICIAL VIDEO]",
    "artist": null,
    "genre": null
  },
  {
    "file": "music/정국 (Jung Kook) 'Seven (feat. Latto)' Official MV.mp3",
    "title": "정국 (Jung Kook) 'Seven (feat. Latto)' Official MV",
    "artist": null,
    "genre": null
  }
];
