// Auto-generated by build.py
const SONGS = [
  {
    "file": "music/Rick Astley - Never Gonna Give You Up (Official Music Video).mp3",
    "title": "Never Gonna Give You Up (Official Music Video)",
    "artist": "Rick Astley",
    "genre": null
  }
];
